#!/bin/bash
# setup.sh: Robust system & profile bootstrapper.
# Usage: sudo ./setup.sh [dev|rev|pwn] [--ssh-key "..."]

set -euo pipefail

# --- Configuration ---
REPO_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
REAL_USER="${SUDO_USER:-$(whoami)}"
USER_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)

# --- Logging ---
log() { echo -e "\033[0;32m[INFO]\033[0m $1"; }
warn() { echo -e "\033[0;33m[WARN]\033[0m $1"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $1"; exit 1; }

# --- Root Guard ---
if [ "$EUID" -ne 0 ]; then
    error "Please run as root: sudo $0"
fi

# ==========================================
# PHASE 1: SYSTEM CONFIGURATION (ROOT)
# ==========================================

install_base_deps() {
    log "Installing base dependencies..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -q
    # stow is added for dotfile management
    apt-get install -y -q ca-certificates curl gnupg unzip git build-essential stow wget
}

install_docker_official() {
    if command -v docker &>/dev/null; then 
        log "Docker is already installed."
        return 0
    fi
    log "Installing Docker (Official Repo)..."

    # Determine the correct upstream ID and codename for Docker's repositories
    . /etc/os-release
    local DOCKER_OS_ID="$ID"
    local DOCKER_CODENAME="$VERSION_CODENAME"

    # For distros like Kali or Parrot that are Debian-based but don't have their own Docker repo.
    if [[ "${PRETTY_NAME}" == *"Parrot"* || "$ID" == "parrot" || "$ID" == "kali" ]]; then
        warn "Docker does not provide a repo for '${PRETTY_NAME}'. Using the upstream Debian 'bookworm' repo instead."
        DOCKER_OS_ID="debian"
        DOCKER_CODENAME="bookworm"
    fi

    # 1. Setup Keyrings using the correct OS ID
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL "https://download.docker.com/linux/${DOCKER_OS_ID}/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # 2. Add Repo using the correct OS ID and Codename
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$DOCKER_OS_ID \
    $DOCKER_CODENAME stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    # 3. Install
    apt-get update -q
    apt-get install -y -q docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    # 4. Permissions
    usermod -aG docker "$REAL_USER"
}

harden_ssh() {
    log "Hardening SSH..."
    local CONFIG_CONTENT="PubkeyAuthentication yes
PasswordAuthentication no
PermitRootLogin no
ChallengeResponseAuthentication no"

    if [ -d "/etc/ssh/sshd_config.d" ] && grep -q "^Include /etc/ssh/sshd_config.d" /etc/ssh/sshd_config; then
        echo "$CONFIG_CONTENT" > /etc/ssh/sshd_config.d/99-hardening.conf
    else
        warn "sshd_config.d not supported or included. Appending to main config."
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        echo "$CONFIG_CONTENT" >> /etc/ssh/sshd_config
    fi
    
    if sshd -t; then
        systemctl restart ssh
    else
        error "SSH Config syntax check failed. Reverting changes..."
        rm -f /etc/ssh/sshd_config.d/99-hardening.conf 2>/dev/null || mv /etc/ssh/sshd_config.bak /etc/ssh/sshd_config
        exit 1
    fi
}

install_mise_system_binary() {
    if command -v mise &>/dev/null; then 
        log "mise is already installed."
        return 0
    fi
    log "Installing Mise binary..."
    
    install -m 0755 -d /etc/apt/keyrings
    wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list > /dev/null
    
    apt-get update -q
    apt-get install -y -q mise
}

# ==========================================
# PHASE 2: USER CONFIGURATION (DE-ELEVATED)
# ==========================================

configure_user_environment() {
    local REPO_DIR="$1"
    shift
    local PROFILES=("$@")
    local CONFIG_FILE="$HOME/.config/mise/config.toml"

    # Must be sourced for mise to be available in the subshell
    source <(mise activate bash)

    echo -e "\033[0;32m[INFO]\033[0m Configuring Mise profiles for user $(whoami)..."

    mkdir -p "$(dirname "$CONFIG_FILE")"
    
    # Generate Config
    cat <<EOF > "$CONFIG_FILE"
# Generated by setup.sh
[env]
# Required for subsequent tool installations within mise
PATH = '$HOME/.local/bin:%s'

[imports]
base = "$REPO_DIR/mise/base.toml"
EOF

    for p in "${PROFILES[@]}"; do
        if [ -f "$REPO_DIR/mise/$p.toml" ]; then
            echo "$p = \"$REPO_DIR/mise/$p.toml\"" >> "$CONFIG_FILE"
        fi
    done

    echo -e "\n[settings]\nexperimental = true" >> "$CONFIG_FILE"

    echo -e "\033[0;32m[INFO]\033[0m Installing tools with mise..."
    mise trust
    mise install -y

    stow_dotfiles "$REPO_DIR"
}

stow_dotfiles() {
    local REPO_DIR="$1"
    echo -e "\033[0;32m[INFO]\033[0m Stowing dotfiles..."
    
    if [ -f "$HOME/.zshrc" ] && [ ! -L "$HOME/.zshrc" ]; then
        echo -e "\033[0;33m[WARN]\033[0m Backing up existing .zshrc to .zshrc.bak..."
        mv "$HOME/.zshrc" "$HOME/.zshrc.bak"
    fi

    # Core dotfiles that should always be stowed
    local CORE_PACKAGES=(zsh tmux eza git vivid nvim alacritty hypr kanshi waybar)

    for pkg in "${CORE_PACKAGES[@]}"; do
        if [ -d "${REPO_DIR}/${pkg}" ]; then
            echo "Stowing '${pkg}'..."
            stow --dir="$REPO_DIR" --target="$HOME" --restow "$pkg" 2>/dev/null || echo -e "\033[0;33m[WARN]\033[0m Stow found conflicts for '${pkg}'. It might be partially stowed."
        fi
    done
}

export -f configure_user_environment
export -f stow_dotfiles

# ==========================================
# MAIN EXECUTION
# ==========================================

# Parse Args
ACTIVE_PROFILES=()
SSH_KEY=""

while [[ $# -gt 0 ]]; do
    case $1 in
        dev|rev|pwn) ACTIVE_PROFILES+=("$1"); shift ;;
        all) ACTIVE_PROFILES+=("dev" "rev" "pwn"); shift ;;
        --ssh-key) SSH_KEY="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# 1. Run Root Tasks
install_base_deps
install_docker_official
install_mise_system_binary
[ -n "$SSH_KEY" ] && harden_ssh

# 2. Add SSH Key (Root task, but affects user file)
if [ -n "$SSH_KEY" ]; then
    mkdir -p "$USER_HOME/.ssh"
    if ! grep -qF "$SSH_KEY" "$USER_HOME/.ssh/authorized_keys" 2>/dev/null; then
        echo "$SSH_KEY" >> "$USER_HOME/.ssh/authorized_keys"
        chown -R "$REAL_USER:$REAL_USER" "$USER_HOME/.ssh"
        chmod 700 "$USER_HOME/.ssh"
        chmod 600 "$USER_HOME/.ssh/authorized_keys"
    fi
fi

# 3. Drop Privileges & Handoff to User
log "Handing off to user '$REAL_USER' for tool and dotfile installation..."
su "$REAL_USER" -c "bash -c 'configure_user_environment \"$REPO_DIR\" ${ACTIVE_PROFILES[*]}'"

log "Setup Complete."
warn "Please log out and log back in for Docker group changes to take effect."
