# Extra env variables
# env = MY_GLOBAL_ENV,setting
# env = NVD_BACKEND,direct
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA (Maxwell/Pascal/Volta without GSP firmware)
env = NVD_BACKEND,egl
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

